### ISSUE TITLE
Nonogram:Minor Graphical bug

### ISSUE THREAD

**Issue by FR1CK1** [kraibse/kraibse.github.io#15]
An empty field is highlighted in Purple. After commenting and uncommenting the field the highlight is white.

**Comment by kraibse** [comment]
Which tile gets highlighted? As far as I know, the last selected tile (with keyboard) stays the active tile even if you are using mouse controls.

**Comment by FR1CK1** [comment]
I mean the highlight in general. The first pic is the normal purple highlight. The second is the highlight, after the field was commented once


![2022-04-20 10_25_46-Mozilla Firefox](https://user-images.githubusercontent.com/103254202/164185095-a5821e8d-0c63-420b-8a44-ddb6f3abaff4.png)
![2022-04-20 10_26_02-Mozilla Firefox](https://user-images.githubusercontent.com/103254202/164185114-affda780-5775-4412-b6fc-3493b79aa062.png)
l

**Comment by kraibse** [comment]
The tile now also correctly displays the correct color on focus (including already set tiles)
